In [1]:
import pandas as pd
#import geoviews as gv
#import geoviews.feature as gf
#import xarray as xr
#from cartopy import crs
import geopandas as gpd
import json
import folium # map rendering library
#import streamlit as st #creating an app
#from streamlit_folium import folium_static 
import numpy as np

In [4]:
df = pd.read_csv("PS_LibreAcces_Personne_activite_202212080954.txt", sep="|")

C:\Users\jb\AppData\Local\Temp\ipykernel_13748\608093414.py:1: DtypeWarning: Columns (28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("PS_LibreAcces_Personne_activite_202212080954.txt", sep="|")

In [7]:
df.drop_duplicates(subset=["Nom d'exercice","Prénom d'exercice"])

,Type d'identifiant PP,Identifiant PP,Identification nationale PP,Code civilité d'exercice,Libellé civilité d'exercice,Code civilité,Libellé civilité,Nom d'exercice,Prénom d'exercice,Code profession,...,Autorité d'enregistrement,Code secteur d'activité,Libellé secteur d'activité,Code section tableau pharmaciens,Libellé section tableau pharmaciens,Code rôle,Libellé rôle,Code genre activité,Libellé genre activité,Unnamed: 56
0,0,010000057,0010000057,NaN,NaN,MME,Madame,BALLUFIN,Audrey,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,010000123,0010000123,NaN,NaN,M,Monsieur,FRAIGNEAU,Laurent,71,...,ARS//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,010000479,0010000479,NaN,NaN,MME,Madame,NICOD HAOUY,Elvine,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,010004729,0010004729,NaN,NaN,MME,Madame,MOUTON,Marine,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,010004992,0010004992,NaN,NaN,MME,Madame,DURY,Morgane,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1860857,8,10108464933,810108464933,NaN,NaN,MME,Madame,BOTEY,LEA,60,...,//ARS,SA01,Etablissement Public de santé,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN
1860858,8,10108466961,810108466961,NaN,NaN,MME,Madame,GRAINDOR,JENNIE,60,...,//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860859,8,10108475558,810108475558,NaN,NaN,MME,Madame,JAILLET,MALAURIE,60,...,//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860860,8,10108476580,810108476580,NaN,NaN,MME,Madame,CONCEICAO,MARIE,60,...,//ARS,SA04,Etab. Privé Non PSPH,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN
1860861,8,10108480681,810108480681,NaN,NaN,MME,Madame,DRICOURT,ELODIE,60,...,//,SA26,Ministère & Serv. déconcentrés,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN

In [8]:
df.columns

Index(['Type d'identifiant PP', 'Identifiant PP',
       'Identification nationale PP', 'Code civilité d'exercice',
       'Libellé civilité d'exercice', 'Code civilité', 'Libellé civilité',
       'Nom d'exercice', 'Prénom d'exercice', 'Code profession',
       'Libellé profession', 'Code catégorie professionnelle',
       'Libellé catégorie professionnelle', 'Code type savoir-faire',
       'Libellé type savoir-faire', 'Code savoir-faire',
       'Libellé savoir-faire', 'Code mode exercice', 'Libellé mode exercice',
       'Numéro SIRET site', 'Numéro SIREN site', 'Numéro FINESS site',
       'Numéro FINESS établissement juridique',
       'Identifiant technique de la structure', 'Raison sociale site',
       'Enseigne commerciale site',
       'Complément destinataire (coord. structure)',
       'Complément point géographique (coord. structure)',
       'Numéro Voie (coord. structure)',
       'Indice répétition voie (coord. structure)',
       'Code type de voie (coord. structure)',
       'Libellé type de voie (coord. structure)',
       'Libellé Voie (coord. structure)',
       'Mention distribution (coord. structure)',
       'Bureau cedex (coord. structure)', 'Code postal (coord. structure)',
       'Code commune (coord. structure)', 'Libellé commune (coord. structure)',
       'Code pays (coord. structure)', 'Libellé pays (coord. structure)',
       'Téléphone (coord. structure)', 'Téléphone 2 (coord. structure)',
       'Télécopie (coord. structure)', 'Adresse e-mail (coord. structure)',
       'Code Département (structure)', 'Libellé Département (structure)',
       'Ancien identifiant de la structure', 'Autorité d'enregistrement',
       'Code secteur d'activité', 'Libellé secteur d'activité',
       'Code section tableau pharmaciens',
       'Libellé section tableau pharmaciens', 'Code rôle', 'Libellé rôle',
       'Code genre activité', 'Libellé genre activité', 'Unnamed: 56'],
      dtype='object')

In [5]:
df

,Type d'identifiant PP,Identifiant PP,Identification nationale PP,Code civilité d'exercice,Libellé civilité d'exercice,Code civilité,Libellé civilité,Nom d'exercice,Prénom d'exercice,Code profession,...,Autorité d'enregistrement,Code secteur d'activité,Libellé secteur d'activité,Code section tableau pharmaciens,Libellé section tableau pharmaciens,Code rôle,Libellé rôle,Code genre activité,Libellé genre activité,Unnamed: 56
0,0,010000057,0010000057,NaN,NaN,MME,Madame,BALLUFIN,Audrey,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,010000123,0010000123,NaN,NaN,M,Monsieur,FRAIGNEAU,Laurent,71,...,ARS//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,010000479,0010000479,NaN,NaN,MME,Madame,NICOD HAOUY,Elvine,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,010004729,0010004729,NaN,NaN,MME,Madame,MOUTON,Marine,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,010004992,0010004992,NaN,NaN,MME,Madame,DURY,Morgane,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1860857,8,10108464933,810108464933,NaN,NaN,MME,Madame,BOTEY,LEA,60,...,//ARS,SA01,Etablissement Public de santé,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN
1860858,8,10108466961,810108466961,NaN,NaN,MME,Madame,GRAINDOR,JENNIE,60,...,//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860859,8,10108475558,810108475558,NaN,NaN,MME,Madame,JAILLET,MALAURIE,60,...,//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860860,8,10108476580,810108476580,NaN,NaN,MME,Madame,CONCEICAO,MARIE,60,...,//ARS,SA04,Etab. Privé Non PSPH,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN
1860861,8,10108480681,810108480681,NaN,NaN,MME,Madame,DRICOURT,ELODIE,60,...,//,SA26,Ministère & Serv. déconcentrés,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN

In [10]:
df.drop_duplicates(subset=["Libellé profession"])["Libellé profession"]

0                             Ostéopathe
5                      Opticien-Lunetier
7                     Assistant dentaire
8              Technicien de Laboratoire
9                            Psychologue
12                      Psychothérapeute
14                        Ergothérapeute
15                           Diététicien
17                      Manipulateur ERM
19                      Assistant social
34                     Audio-Prothésiste
45                       Psychomotricien
68                         Orthophoniste
118                          Orthoptiste
156                     Orthoprothésiste
281              Orthopédiste-Orthésiste
444                      Podo-Orthésiste
866                        Chiropracteur
2049                          Pharmacien
2052                             Médecin
2053                          Sage-Femme
2062                 Chirurgien-Dentiste
3516            Masseur-Kinésithérapeute
3815                  Pédicure-Podologue
3881                           Infirmier
8109                          Oculariste
8388                         Epithésiste
14037    Acteur caractérisé par son rôle
Name: Libellé profession, dtype: object

In [50]:
df.drop_duplicates(subset=["Libellé savoir-faire"])["Libellé savoir-faire"]

0                                                       NaN
2052                       Spécialiste en Médecine Générale
2055                                       Radio-diagnostic
2056                      Gastro-entérologie et hépatologie
2058                                   Chirurgie urologique
                                ...
192599           Biologie médicale option biologie générale
228828           Biologie médicale option agents infectieux
287271             Chirurgie maxillo-faciale (réforme 2017)
482613    Biologie médicale option hématologie et immuno...
846917    Chirurgie pédiatrique option orthopédie pédiat...
Name: Libellé savoir-faire, Length: 83, dtype: object

In [15]:
df2 = df[df["Libellé profession"] == "Médecin"]

In [16]:
df2.drop_duplicates(subset=["Nom d'exercice","Prénom d'exercice"])

,Type d'identifiant PP,Identifiant PP,Identification nationale PP,Code civilité d'exercice,Libellé civilité d'exercice,Code civilité,Libellé civilité,Nom d'exercice,Prénom d'exercice,Code profession,...,Autorité d'enregistrement,Code secteur d'activité,Libellé secteur d'activité,Code section tableau pharmaciens,Libellé section tableau pharmaciens,Code rôle,Libellé rôle,Code genre activité,Libellé genre activité,Unnamed: 56
2052,8,10000013028,810000013028,DR,Docteur,MME,Madame,HELENE-PELAGE,JEANNIE,10,...,CNOM/CNOM/CNOM,SA07,Cabinet individuel,NaN,NaN,FON-01,Titulaire de cabinet,GENR01,Activité standard de soin ou de pharmacien,NaN
2055,8,10000023373,810000023373,DR,Docteur,M,Monsieur,NATALI,BRUNO,10,...,CNOM/CNOM/ARS,SA04,Etab. Privé Non PSPH,NaN,NaN,FON-17,Collaborateur,GENR01,Activité standard de soin ou de pharmacien,NaN
2056,8,10000025832,810000025832,DR,Docteur,MME,Madame,DURAND,MAGALI,10,...,CNOM/CNOM/CNOM,SA09,Exercice en Société,NaN,NaN,FON-02,Associé dans une société d'exercice ou SCP,GENR01,Activité standard de soin ou de pharmacien,NaN
2058,8,10000033984,810000033984,DR,Docteur,M,Monsieur,BRAUD,FREDERIC,10,...,CNOM/CNOM/CNOM,SA09,Exercice en Société,NaN,NaN,FON-02,Associé dans une société d'exercice ou SCP,GENR01,Activité standard de soin ou de pharmacien,NaN
2060,8,10000038983,810000038983,DR,Docteur,M,Monsieur,LARIFLA,LAURENT,10,...,CNOM/CNOM/CNOM,SA07,Cabinet individuel,NaN,NaN,FON-01,Titulaire de cabinet,GENR01,Activité standard de soin ou de pharmacien,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1860774,8,10108217554,810108217554,NaN,NaN,MME,Madame,LE CAM,Elena,10,...,CNOM//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860775,8,10108219360,810108219360,NaN,NaN,M,Monsieur,HERGAT,Eliott,10,...,CNOM//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860776,8,10108229120,810108229120,NaN,NaN,MME,Madame,EBERHARDT,Marie,10,...,CNOM//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860801,8,10108297663,810108297663,DR,Docteur,M,Monsieur,DIARRA,Cheick Oumar Tidiani,10,...,CNOM/CNOM/ARS,SA01,Etablissement Public de santé,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN
1860812,8,10108329904,810108329904,DR,Docteur,M,Monsieur,BENOSMAN,Mohammed Reda,10,...,CNOM/CNOM/ARS,SA01,Etablissement Public de santé,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN

In [36]:

df3 = pd.read_csv("PS_LibreAcces_Personne_activite_202212080954.txt", sep="|")

C:\Users\jb\AppData\Local\Temp\ipykernel_13748\3187323798.py:1: DtypeWarning: Columns (28,35) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv("PS_LibreAcces_Personne_activite_202212080954.txt", sep="|")

In [37]:
df3.columns

Index(['Type d'identifiant PP', 'Identifiant PP',
       'Identification nationale PP', 'Code civilité d'exercice',
       'Libellé civilité d'exercice', 'Code civilité', 'Libellé civilité',
       'Nom d'exercice', 'Prénom d'exercice', 'Code profession',
       'Libellé profession', 'Code catégorie professionnelle',
       'Libellé catégorie professionnelle', 'Code type savoir-faire',
       'Libellé type savoir-faire', 'Code savoir-faire',
       'Libellé savoir-faire', 'Code mode exercice', 'Libellé mode exercice',
       'Numéro SIRET site', 'Numéro SIREN site', 'Numéro FINESS site',
       'Numéro FINESS établissement juridique',
       'Identifiant technique de la structure', 'Raison sociale site',
       'Enseigne commerciale site',
       'Complément destinataire (coord. structure)',
       'Complément point géographique (coord. structure)',
       'Numéro Voie (coord. structure)',
       'Indice répétition voie (coord. structure)',
       'Code type de voie (coord. structure)',
       'Libellé type de voie (coord. structure)',
       'Libellé Voie (coord. structure)',
       'Mention distribution (coord. structure)',
       'Bureau cedex (coord. structure)', 'Code postal (coord. structure)',
       'Code commune (coord. structure)', 'Libellé commune (coord. structure)',
       'Code pays (coord. structure)', 'Libellé pays (coord. structure)',
       'Téléphone (coord. structure)', 'Téléphone 2 (coord. structure)',
       'Télécopie (coord. structure)', 'Adresse e-mail (coord. structure)',
       'Code Département (structure)', 'Libellé Département (structure)',
       'Ancien identifiant de la structure', 'Autorité d'enregistrement',
       'Code secteur d'activité', 'Libellé secteur d'activité',
       'Code section tableau pharmaciens',
       'Libellé section tableau pharmaciens', 'Code rôle', 'Libellé rôle',
       'Code genre activité', 'Libellé genre activité', 'Unnamed: 56'],
      dtype='object')

In [38]:
df3

,Type d'identifiant PP,Identifiant PP,Identification nationale PP,Code civilité d'exercice,Libellé civilité d'exercice,Code civilité,Libellé civilité,Nom d'exercice,Prénom d'exercice,Code profession,...,Autorité d'enregistrement,Code secteur d'activité,Libellé secteur d'activité,Code section tableau pharmaciens,Libellé section tableau pharmaciens,Code rôle,Libellé rôle,Code genre activité,Libellé genre activité,Unnamed: 56
0,0,010000057,0010000057,NaN,NaN,MME,Madame,BALLUFIN,Audrey,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,010000123,0010000123,NaN,NaN,M,Monsieur,FRAIGNEAU,Laurent,71,...,ARS//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,010000479,0010000479,NaN,NaN,MME,Madame,NICOD HAOUY,Elvine,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,010004729,0010004729,NaN,NaN,MME,Madame,MOUTON,Marine,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,010004992,0010004992,NaN,NaN,MME,Madame,DURY,Morgane,71,...,ARS/CPAM/CPAM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1860857,8,10108464933,810108464933,NaN,NaN,MME,Madame,BOTEY,LEA,60,...,//ARS,SA01,Etablissement Public de santé,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN
1860858,8,10108466961,810108466961,NaN,NaN,MME,Madame,GRAINDOR,JENNIE,60,...,//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860859,8,10108475558,810108475558,NaN,NaN,MME,Madame,JAILLET,MALAURIE,60,...,//,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860860,8,10108476580,810108476580,NaN,NaN,MME,Madame,CONCEICAO,MARIE,60,...,//ARS,SA04,Etab. Privé Non PSPH,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN
1860861,8,10108480681,810108480681,NaN,NaN,MME,Madame,DRICOURT,ELODIE,60,...,//,SA26,Ministère & Serv. déconcentrés,NaN,NaN,FON-33,Salarié en poste fixe,GENR01,Activité standard de soin ou de pharmacien,NaN

In [47]:

df5 = df3.groupby("Libellé Département (structure)")["Libellé Département (structure)"].count().reset_index(name="count")

In [48]:
df5

Empty DataFrame
Columns: [Libellé Département (structure), count]
Index: []

In [43]:
df4 = df3.groupby("Libellé profession")["Libellé profession"].count().reset_index(name="count")

In [44]:
df4

                 Libellé profession   count
0   Acteur caractérisé par son rôle     203
1                Assistant dentaire   17374
2                  Assistant social   49045
3                 Audio-Prothésiste    8371
4                     Chiropracteur    1902
5               Chirurgien-Dentiste   66923
6                       Diététicien   24836
7                       Epithésiste     103
8                    Ergothérapeute   19686
9                         Infirmier  525334
10                 Manipulateur ERM   43037
11         Masseur-Kinésithérapeute  124006
12                          Médecin  486449
13                       Oculariste      76
14                Opticien-Lunetier   57170
15                    Orthophoniste   32157
16                 Orthoprothésiste    1909
17                      Orthoptiste    8150
18          Orthopédiste-Orthésiste    2846
19                       Ostéopathe   39489
20                       Pharmacien   82824
21                  Podo-Orthésiste     888
22                      Psychologue  122305
23                  Psychomotricien   22839
24                 Psychothérapeute   12457
25               Pédicure-Podologue   17295
26                       Sage-Femme   36951
27        Technicien de Laboratoire   56237

In [51]:
df5 = df3.groupby("Libellé savoir-faire")["Libellé savoir-faire"].count().reset_index(name="count")

In [52]:
df5

                          Libellé savoir-faire  count
0                                 Allergologie    529
1          Anatomie et cytologie pathologiques   4985
2                       Anesthesie-réanimation  21036
3                            Biologie médicale   4236
4   Biologie médicale option agents infectieux      5
..                                         ...    ...
77                                Rhumatologie   4896
78          Santé publique et médecine sociale   2666
79            Spécialiste en Médecine Générale  96911
80                                Stomatologie   1421
81                                    Urologie     31

[82 rows x 2 columns]